### ISSUE TITLE
Issue with running using docker

### ISSUE THREAD

**Issue by nathanmerry** [domainmod/domainmod#166]
Hello,

I am attempting to run your service using Docker; however, I am having issues with the initial setup. I am running this all on my local machine.

When I attempt to run docker-compose up -d and view it locally, I receive a 500 error. After inspecting the logs, I can see the error `chmod: cannot access '/var/www/html/temp'`: No such file or directory.

Then when I open the server in the browser, I see the following logs:

```
PHP Warning: require_once(/var/www/html/_includes/config.inc.php): Failed to open stream: No such file or directory in /var/www/html/index.php on line 25
PHP Fatal error: Uncaught Error: Failed opening required '/var/www/html/_includes/config.inc.php' (include_path='.:/usr/local/lib/php') in /var/www/html/index.php:25\nStack trace:\n#0 {main}\n thrown in /var/www/html/index.php on line 25

```

Do you know what the issue could be?

My docker-compose.yml:

```
services:
  app:
    image: domainmod/domainmod:latest
    container_name: domainmod_app
    depends_on:
      - db
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Vancouver
      - DOMAINMOD_WEB_ROOT=
      - DOMAINMOD_DATABASE_HOST=db
      - DOMAINMOD_DATABASE=domainmod
      - DOMAINMOD_USER=domainmod
      - DOMAINMOD_PASSWORD=password1
    volumes:
      - ./application:/var/www/html
    ports:
      - 8080:80
    restart: unless-stopped

  db:
    image: ghcr.io/linuxserver/mariadb:alpine
    container_name: domainmod_db
    environment:
      - PUID=501
      - PGID=20
      - TZ=America/Vancouver
      - MYSQL_DATABASE=domainmod
      - MYSQL_USER=domainmod
      - MYSQL_PASSWORD=password1
      - MYSQL_ROOT_PASSWORD=password2
    volumes:
      - ./database:/config
    ports:
      - 3306
    restart: unless-stopped
```
