### ISSUE TITLE
Feature Request: CSV import

### ISSUE THREAD

**Issue by Splix76** [domainmod/domainmod#57]
Since most registrars support an export of a .csv file, allowing import from a .csv file makes sense.

**Comment by Splix76** [comment]
Based on the database values from the domains table, this could be done from the account page, a 'csv-import' button could allow me to attach a file. File would only need domain name and expiration date in yyyy-mm-dd format, which can be confirmed via pop up when you click it.

This allows me to run a full export of domains from the registrar, modify the date fields if needed, cut out the un-needed data and import a list of domains with dates and is less intrusive than an API linked account.

```
              id: 5
        owner_id: 1
    registrar_id: 3
      account_id: 3
          domain: domainname.com
             tld: shop
     expiry_date: 2018-02-01
          cat_id: 1
          fee_id: 2
      total_cost: 9.99
          dns_id: 1
           ip_id: 1
      hosting_id: 1
        function: 
           notes: 
       autorenew: 0
         privacy: 0
          active: 1
       fee_fixed: 1
creation_type_id: 2
      created_by: 2
     insert_time: 2018-01-24 23:03:00
     update_time: 1978-01-23 00:00:00
```
